### ISSUE TITLE
Setting system as the "modules" value doesn't make a difference.

### ISSUE THREAD

**Issue by vangorra** [pbastowski/angular-meteor-babel#10]
Using the following configuration and my server side .js files are getting transpiled to commonjs, not systemjs.

``` json
// babel.json
{
  "verbose": true,
  "debug": false,
  "modules": "system",
  "stage": 0,
  "extensions": ["js"]
}
```

**Comment by pbastowski** [comment]
That's correct for the currently published package. It only supports SystemJS on the client side.

However, I have a branch that is being tested, 
https://github.com/pbastowski/angular-meteor-babel/tree/feature/server-systemjs
which supports SystemJS also on the server side. You will need to clone the repo into your packages folder and then checkout **feature/server-systemjs**.

You will also need to clone 
https://github.com/pbastowski/systemjs/tree/feature/server-side
into your packages folder and then checkout **feature/server-side**

Read the updated angular-babel README for how to use the new feature and let me know if this helps.

**Comment by vangorra** [comment]
Granted the concept of using a module loader on Meteor is pretty new. However the advantages are substantial. Out of curiosity, I've noticed several meteor packages seemingly only support module loaders on the client side. Do you have any insights into why this is? It makes it really difficult to write code for both client and server.

**Comment by pbastowski** [comment]
@vangorra 

There are some issues with using SystemJS on the Meteor backend, which I have experienced myself. For example, when I want to use `new Mongo.Collection(...)`, Meteor sometimes complains about having to run Meteor code in a Fiber. I haven't been able to fully get this working, which is why I haven't published the `server-systemjs` branch yet. Perhaps others have encountered similar issues.
