### ISSUE TITLE
async / await doesn't work

### ISSUE THREAD

**Issue by luncasu** [pbastowski/angular-meteor-babel#19]
Upgraded to Meteor 1.3 & pbastowski:angular-babel@1.3.1 particularly to use async / await pattern.
However I get "**TypeError: Object [object Object] has no method 'awrap'**" error when **await** function is being called during execution. (project compilation is fine)

I have configures Babel to stage 2 but no luck. Any idea what I'm missing?
#### Meteor code

Meteor.methods({  
  getUser: async () => {
      try {
       // Get user from db by mongoose model - exec() returns a promise
        **const user = await User.findById( 'y7zSQjpGZeQfhjF82' ).lean().exec();**
        return user;
      }
      catch (error) {
        console.log( error.stack );
        throw new Meteor.Error('500', `${ error }`);
      }
  }
});

**#Babel config**:
 {
    "debug": true,
    "verbose": false,
    "stage": 2,
    "modules": "common",
    "blacklist": [
        "useStrict"
    ],
    "extensions": [
        "js"
    ]

[MeteorAwaitError.txt](https://github.com/pbastowski/angular-meteor-babel/files/193859/MeteorAwaitError.txt)

**Comment by pbastowski** [comment]
@luncasu 

I've just pushed v1.3.2 with a change that reverts a regression, which occurred somewhere along the way. The required functionality was to overwrite the default regenerator runtime supplied by Meteor, because it does not support async/await and some other stuff, with a custom version, which does.

Could you please check and let me know if it helps?

Thanks.

**Comment by luncasu** [comment]
v1.3.2 fixed the issue. Thanks a lot.
My code looks much better now.
