### ISSUE TITLE
Babel and bower

### ISSUE THREAD

**Issue by sauliuni** [pbastowski/angular-meteor-babel#20]
In my project ( meteor + angularjs 1) i use bower for several packages, like ngDraggable. Now i want to upgrade my project to meteor 1.3 and use npm + native bower from npm in my project. After installing bower i run 'bower' in the project root, so that bower installs the packages. If then i start the server, i get errors like:

`[BABEL] Note: The code generator has deoptimised the styling of "/bower_components/jquery/dist/jquery.js" as it exceeds the max of "100KB".`

or

`{ [SyntaxError: /bower_components/jquery/src/intro.js: Unexpected token (45:0)]
  pos: 1376,
  loc: { line: 45, column: 0 },
  _babel: true,
  codeFrame: '  43 | // you try to trace through "use strict" call chains. (#13335)\n  44 | //"use strict";\n> 45 | \n     | ^' }`

I tried to create babel.json with following sourcem  but it still goes inside the folder:

`{
  "ignore": [
    "bower_components/**/*.js"
  ]
}`

**Comment by pbastowski** [comment]
Hi @sauliuni 
Do not install from bower, because Meteor 1.3 does not support it. Only use NPM. This will solve lots of issues for you in the first place.

```
[BABEL] Note: The code generator has deoptimised the styling of "/bower_components/jquery/dist/jquery.js" as it exceeds the max of "100KB".
```

The above is just an info and can be safely ignored.

The jquery related errors are there, because you used bower.

Also, you may not need to install jquery, because Meteor already includes it for you.

**Comment by pbastowski** [comment]
Closing due to lack of response from initiator.
