### ISSUE TITLE
'import' and 'export' may only appear at the top level

### ISSUE THREAD

**Issue by auterium** [pbastowski/angular-meteor-babel#27]
As of Meteor version 1.3.3 "import statements in application modules are no longer restricted to the top level, and may now appear inside conditional statements (e.g. if (Meteor.isServer) { import ... }) or in nested scopes." which is from the ecmascript package that Meteor uses by default.

Looking through the packages I found that this one uses babel-core 5.8.23 directly and Meteor's ecmascript package uses their own wrapper (NPM meteor-babel) that uses babel-core ~6.9.1. Is it possible to use meteor-babel instead of babel-core directly? That way any improvements done by MDG will be available in this package, thus more similar to what's shown on the Meteor history.md file.

Thanks

**Comment by pbastowski** [comment]
Hi @auterium 
I am actually trying to drop support for my `angular-meteor-babel` package, because it is now possible to add any functionality to `ecmascript` through the use of the `.babelrc` config file. See notes for Meteor 1.3.3.

The only thing that is not supported through `.babelrc` is `ng-annotate`.

Do you need `ng-annotate` support in your project?

**Comment by auterium** [comment]
Hi @pbastowski, thanks for the answer. I've figured out how to use the ecmascript package directly without the ng-annotate and it works fine. I do miss the ng-annotate support as it's very helpful, but it's not the end of the world without it.

I'm not familiar with babel, so I'm not sure how to add functionality to ecmascript with .babelrc.

Any help, guidance, or references on adding ng-annotate to Angular-Meteor would be much appreciated.

**Comment by pbastowski** [comment]
Firstly, it's good that you worked this out for yourself. You always learn something that way.

Secondly, unfortunately there is no easy way to add ng-annotate to Meteor while using the `ecmascript` package at the same time, which is why I created my `angular-babel` package in the first place.

There may be a Babel plugin that does this, but it would have to be configured in the `.babelrc` file.

**Comment by auterium** [comment]
Thanks @pbastowski, I don't like to wait for someone else to figure out things for me if I can do so, or at least not before trying it myself.

Anyway, thanks for the help, I'll try to convince Uri Goldstein to change the tutorials to include both options.
