### ISSUE TITLE
File order with mquandalle:bower

### ISSUE THREAD

**Issue by hlehmann** [pbastowski/angular-meteor-babel#4]
Combine with mquandalle:bower, depedencies are loaded after app files. Is it possible to make packages/\* firsts in line ?

**Comment by pbastowski** [comment]
A repo for me to look at would help here, as I am not exactly sure what you mean. For instance, what "dependencies" are you referring to? Something to do with Bower perhaps? Or maybe you mean your own Meteor packages and that's why you mention "packages/*"?

So, yeah, not sure what you mean exactly.

As far as ordering files, a compiler plugin, such as this package, to my knowledge has no control over the order in which files get transpiled. Meteor determines the order and then sends a list of files to the plugin to transpile. Perhaps you can look into Meteor's [file load order](http://docs.meteor.com/#/full/fileloadorder) for some help.

**Comment by pbastowski** [comment]
Closing due to no response from reporter. Reopen if needed.
