### ISSUE TITLE
Conflict error

### ISSUE THREAD

**Issue by mrjason** [pbastowski/angular-meteor-babel#5]
I upgraded to Meteor 1.2 and now I am getting the following conflict error:

error: conflict: two packages included in the app (pbastowski:angular-babel and ecmascript) are both trying to handle *.js

**Comment by mrjason** [comment]
i see there is a ng-babel now and it is intended for meteor 1.2

**Comment by pbastowski** [comment]
Update: I re-read your message, above, and noticed that it is indeed the `ecmascript` package that is causing the error. So, here is my updated reply.

The `pbastowski:angular-babel` package that you installed originally is the correct one. What you do need to do is to remove Meteor's own `ecmascript` package, because it also tries to compile `.js` files, thus causing the error. `pbastowski:angular-babel` includes specific functionality that is not available with `ecmascript, most notably as ES7 decorators and`ng-annotate`.

If you don't need ES7 decorators and/or don't care for `ng-annotate` then feel free to keep using the `ecmascript` package instead.
