### ISSUE TITLE
Unexpected character '#' (1:0) Error when building with Android

### ISSUE THREAD

**Issue by lokibg2** [pbastowski/angular-meteor-babel#8]
Urgent help required!! I have been workin on this app using meteor and angular. Everything works fine as long as I haven't added the platform android. Once I did it and tried to build my app, I'm getting the below error.

While processing files with pbastowski:angular-babel (for target
   web.browser):
   packages/compileNGScript/plugin/ng-script-compiler.js:101:1: error: couldn't
   process source due to parse error: 

   Unexpected character '#' (1:0)
   at processFile
   (packages/compileNGScript/plugin/ng-script-compiler.js:101:1)
   at Array.forEach (native)
   at Object.processFiles
   (packages/compileNGScript/plugin/ng-script-compiler.js:38:1)

**Comment by pbastowski** [comment]
Can you please upload your repo and provide a link to it, so, I can have a look for you. Or otherwise, we can do a screen share on google hangouts, if you prefer.

Update: Do you know which file was being processed when the error was produced?

To enable the printing of file names to the console as they are compiled by Babel you need to add

``` json
"verbose": true
```

to "babel.json" and then restart Meteor. If you don't yet have "babel.json" then add it to your project root folder and put this in it:

``` json
{
    "verbose": true
}
```

Then, restart Meteor.

**Comment by pbastowski** [comment]
Closing due to lack of response.

**Comment by Laurisylva** [comment]
I had the same problem than lokibg2.

I installed ng-showdown with bower and that error appeared because of the file "client/lib/bower_components/showdown/bin/showdown.js" who contains

```
#!/usr/bin/env node
require('../src/cli/cli');
```

I removed the first line but in the browser, the console prints then :

```
Uncaught Error: ng-showdown was not loaded because one of its dependencies (AngularJS or Showdown) was not met
(anonymous function)
@ ng-showdown.min.js:3(anonymous function)
@ ng-showdown.min.js:3(anonymous function)
@ ng-showdown.min.js:3(anonymous function)
@ ng-showdown.min.js:3
showdown.js:2
Uncaught ReferenceError: require is not defined
```

I have no idea what to do.

**Comment by pbastowski** [comment]
@LordCaudralys 

Looking at your two sample lines from showdown.js (which sits in a bin folder), this looks to me like a `bash` script or a file meant for nodejs, not the browser.

The [showdown README](https://www.npmjs.com/package/showdown#browser) gives an example of how to use showdown in the browser:

``` js
var converter = new showdown.Converter(),
    text      = '#hello, markdown!',
    html      = converter.makeHtml(text);
```

If I may suggest, have another good read through the showdown README and try again. If it still does not work, perhaps try installing showdown with Npm, instead of bower. And try again.

**Comment by liadlivnat** [comment]
Guys is this issue solve? i get the same error without th ng-showdown, seems like meteor trying to compile node_modules under cordova folder, any idea why?
how can i avoid it?

**Comment by pbastowski** [comment]
I haven't heard back from the reported since he created the issue, so, I don't know if it is solved.

What version of Meteor are you using?

Without seeing your repo I can't help much. So, if you could provide a link to it then I can have a look.

Also, in case you are working with Android, I don't have an Android device to test with. So, I can't help you much with that, unfortunately.

**Comment by doronsever** [comment]
This is happening to me also(using mupx on codeship)

This is the log(verbose)

Errors prevented bundling:
While processing files with pbastowski:angular-babel (for target web.browser):
packages/compileNGScript_plugin.js:116:23: error: couldn't process source due
to parse error: 

Unexpected character '#' (1:0)
at processFile (packages/compileNGScript_plugin.js:116:23)
at Array.forEach (native)
at Object.processFiles (packages/compileNGScript_plugin.js:48:11)

While processing files with pbastowski:angular-babel (for target
os.linux.x86_64):
packages/compileNGScript_plugin.js:116:23: error: couldn't process source due
to parse error: 

Unexpected character '#' (1:0)
at processFile (packages/compileNGScript_plugin.js:116:23)
at Array.forEach (native)
at Object.processFiles (packages/compileNGScript_plugin.js:48:11)

**Comment by pbastowski** [comment]
I will look into this issue over the coming weekend.

**Comment by doronsever** [comment]
I finally got this to work.
Turns out Codeship are adding 2 js files(They are 100% not on my repository) when they clone the build:
phantom_runner.js
start_test.js

So at the deployment stage i just remove it (rm -rf) and now everything works as expected.
Hope it will help someone in the future.

10x a lot though!

**Comment by mariohmol** [comment]
Same here, using OSX was easy to reproduce:
- meteor create simple-todos
- meteor add angular
- meteor remove blaze-html-templates ecmascript
- meteor

Here are my versions

> Meteor 1.3.2.4
> angular                1.3.10  Everything you need to use AngularJS in your Meteor app
> autopublish            1.0.7  (For prototyping only) Publish the entire database to all clients
> es5-shim               4.5.10  Shims and polyfills to improve ECMAScript 5 support
> insecure               1.0.7  (For prototyping only) Allow all database writes from the client
> jquery                 1.11.8  Manipulate the DOM using CSS selectors
> meteor-base            1.0.4  Packages that every Meteor app needs
> mobile-experience      1.0.4  Packages for a great mobile user experience
> mongo                  1.1.7  Adaptor for using MongoDB and Minimongo over DDP
> reactive-var           1.0.9  Reactive variable
> standard-minifier-css  1.0.6  Standard css minifier used with Meteor apps by default.
> standard-minifier-js   1.0.6  Standard javascript minifiers used with Meteor apps by default.
> tracker                1.0.13  Dependency tracker to allow reactive callbacks

Showing the error:

`Errors prevented startup:

While processing files with pbastowski:angular-babel (for target web.browser):
packages/compileNGScript/plugin/ng-script-compiler.js:101:1: error: couldn't process source due to parse error: 

Unexpected character '#' (1:0)
  at processFile (packages/compileNGScript/plugin/ng-script-compiler.js:101:1)
  at Array.forEach (native)
  at Object.processFiles (packages/compileNGScript/plugin/ng-script-compiler.js:38:1)

While processing files with pbastowski:angular-babel (for target os.osx.x86_64):
packages/compileNGScript/plugin/ng-script-compiler.js:101:1: error: couldn't process source due to parse error: 

Unexpected character '#' (1:0)
  at processFile (packages/compileNGScript/plugin/ng-script-compiler.js:101:1)
  at Array.forEach (native)
  at Object.processFiles (packages/compileNGScript/plugin/ng-script-compiler.js:38:1)`

**Comment by pbastowski** [comment]
@mariohmol 
You have to also 

```
meteor add modules
```

The modules package is what gives you the ability to `import ... from`.

Also, be aware that by removing `blaze-html-templates` the blaze template portion of this demo app won't work.

**Comment by mariohmol** [comment]
I had a project , that were basic this example but i had same error after adding modules.

About removing `baze-html-templates`, i followed instructions that are here:
- https://github.com/urigo/angular-meteor/

I had to remove my project, create again and after running `meteor add modules` it worked.

I opened a issue in angular-meteor so them can include add modules in readme.
- https://github.com/Urigo/angular-meteor/issues/1360
